name: Create Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Comprimir archivos
      run: zip -r project-worship.zip ./
    - name: Crear release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release create $(jq -r '.version' package.json) --generate-notes project-worship.zip
    - name: Subir archivo
      uses: actions/upload-artifact@v2
      with:
        name: project-worship
        path: ./project-worship.zip
